controllers:
    resource:
        path: ../src/Api/Controller/
        namespace: Api\Controller
    type: attribute

api_login_check:
    path: /api/v1/auth/login

api_token_invalidate:
    path: /api/v1/logout